import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { runPostDissection } from './lulua_post_dissecter.mjs';
import { runAccountAudit } from './lulua_account_auditor.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BASE_DIR = path.resolve(__dirname, '../../../');
const INBOX_DIR = path.join(BASE_DIR, 'lulua-pipeline/00-Inbox');
const MEMORY_DIR = path.join(BASE_DIR, 'lulua-pipeline/02-Memory');
const DISSECT_NOTE = path.join(INBOX_DIR, '_NEW_POST_DISSECTION.md');
const AUDIT_NOTE = path.join(INBOX_DIR, '_ACCOUNT_AUDIT_BRIEFING.md');

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const lines = match[1].split('\n');
  const metadata = {};

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#') && trimmed.includes(':')) {
      const [key, ...valParts] = trimmed.split(':');
      const val = valParts.join(':').trim().replace(/^["']|["']$/g, '');
      metadata[key.trim()] = val;
    }
  }

  return metadata;
}

let isDissecting = false;

async function checkInboxNotes() {
  // Check Account Audit note
  if (fs.existsSync(AUDIT_NOTE)) {
    const content = fs.readFileSync(AUDIT_NOTE, 'utf8');
    const meta = parseFrontmatter(content);

    if (meta.status === 'ready' && meta.handle && meta.handle.trim()) {
      console.log(`📥 [Note Watcher] Detected status: ready for account audit (@${meta.handle})`);
      
      // Extract human notes section
      const notesIdx = content.indexOf('## 💰 Monetization & Funnel Notes');
      const humanNotes = notesIdx !== -1 ? content.substring(notesIdx) : '';

      await runAccountAudit(meta.handle, meta.platform || 'x', humanNotes);

      // Reset template
      const template = `---
status: draft
handle: ""
platform: "x"
---

# Account Audit Template

## 📊 Beidou Quantitative Data (Auto-Filled)

## 🔗 Surface Profile Info (Auto-Filled)

---------------------------------------------------------
## 💰 Monetization & Funnel Notes (Human Input)
`;
      fs.writeFileSync(AUDIT_NOTE, template);
    }
  }

  // Check Post Dissection note (Exact Event Post Pattern: 00-Inbox -> 02-Memory -> Recreate Inbox ONLY after completion)
  if (!isDissecting && fs.existsSync(DISSECT_NOTE)) {
    const content = fs.readFileSync(DISSECT_NOTE, 'utf8');
    const meta = parseFrontmatter(content);

    if (meta.status === 'ready' && (meta.url || content.includes('http'))) {
      isDissecting = true;
      console.log(`📥 [Note Watcher] Detected status: ready for post dissection. Moving to 02-Memory...`);
      
      if (!fs.existsSync(MEMORY_DIR)) {
        fs.mkdirSync(MEMORY_DIR, { recursive: true });
      }

      const timestamp = Date.now();
      const processingPath = path.join(MEMORY_DIR, `processing-dissect-${timestamp}.md`);

      // 1. Move note out of 00-Inbox to 02-Memory (Locks file from re-triggering)
      fs.renameSync(DISSECT_NOTE, processingPath);

      // 2. Process the moved file inside 02-Memory
      const processingContent = fs.readFileSync(processingPath, 'utf8');
       const processingMeta = parseFrontmatter(processingContent);
      const urlMatch = processingContent.match(/https?:\/\/[^\s\)\>]+/i);
      const frontmatterUrl = (processingMeta.url && processingMeta.url.trim()) ? processingMeta.url.trim() : null;
      const postCount = parseInt(processingMeta.post_count, 10) || 0;
      const bodyContent = processingContent.replace(/^---\n[\s\S]*?\n---\n?/, '').trim();
      const userText = bodyContent
        .replace(/## 📌 Target Post Content \/ URL\n?/gi, '')
        .replace(/<!--[\s\S]*?-->/g, '')
        .replace(/## 📐 Extracted Structural Wireframe[\s\S]*$/i, '')
        .replace(/# Post Dissection Template\n?/gi, '')
        .trim();
      const hasManualText = userText.length > 50;
      const target = hasManualText
        ? (frontmatterUrl ? frontmatterUrl + '\n\n' + userText : userText)
        : (frontmatterUrl || (urlMatch ? urlMatch[0] : processingContent));

      try {
        await runPostDissection(target, processingMeta.platform || 'x', postCount);

        // 3. Remove temporary processing note from 02-Memory once saved to 01-Style-Bank
        if (fs.existsSync(processingPath)) {
          fs.unlinkSync(processingPath);
        }
      } catch (err) {
        console.error(`❌ Dissection execution error:`, err.message);
      } finally {
        // 4. Re-create the fresh blank template in 00-Inbox ONLY AFTER completion!
        const blankTemplate = `---
status: draft
url: ""
platform: "x"
post_count: ""
---

# Post Dissection Template

## 📌 Target Post Content / URL
<!-- Paste URL or post text here -->


## 📐 Extracted Structural Wireframe (Lulua Output)
<!-- Generated by Lulua when status is ready -->
`;
        fs.writeFileSync(DISSECT_NOTE, blankTemplate);
        isDissecting = false;
        console.log(`✨ [Note Watcher] Dissection complete! Re-created clean template in 00-Inbox.`);
      }
    }
  }
}

// Start continuous polling / watching
console.log('👀 [Lulua] Starting Obsidian Inbox Note Watcher Daemon (00-Inbox -> 02-Memory -> 01-Style-Bank)...');
setInterval(checkInboxNotes, 5000);
checkInboxNotes();
